dist: trusty
sudo: required
language: cpp

os:
- linux

compiler:
- gcc

branches:
  only:
    - dev_1

install:
  - source ci/install-linux.sh

script:
  - mkdir tmp
  - cd tmp
  - cmake ..
  - make
  - ./tests --output-on-failure